POSTGRES_USER: postgres
POSTGRES_PASSWORD: "998915309764"
POSTGRES_DB: yuk_hotel_development
TELEGRAM_TOKEN: 6835423194:AAFILqqn_Bj0S5XyGkpBZFmjgEdMlxasuEM
TELEGRAM_CHAT_ID: -4062870742
HOST_URL: host url